NPCs/Mutant.cs
also tweaked his "selling my own summon" line
=> mutant boosts post-mutant

Fargowiltas.cs
=> Census Support

Fargowiltas.cs, Fargowiltas.csproj, Items/Misc/Stats.cs, Items/Misc/SuperDummy.cs, NPCs/SuperDummy.cs
still doesn't work in multiplayer :echprimebegone:
=> new super dummy method

Items/Summons/Abom/CursedSextant.cs, NPCs/Abominationn.cs, description.txt
Bloody Tear's younger, uglier brother
=> Cursed Sextant

Items/Misc/SuperDummy.cs, NPCs/SuperDummy.cs
=> Actually working super dummy mp syncing

Items/Misc/SuperDummy.cs, NPCs/SuperDummy.cs
Super dummies now have more hp so they don't die when they shouldn't
=> Super dummies don't die when they shouldn't

NPCs/LumberJack.cs
=> tree treasures: typo correction, added the birds

UI/UIDragablePanel.cs
=> Bettified UI

UI/UIDragablePanel.cs
=> Awesomerified UI; it's now more awesomer

FargoPlayer.cs, FargoRecipes.cs, Fargowiltas.cs, Items/CaughtNPCs/CaughtNPCItem.cs, Items/FargoGlobalItem.cs, Items/Misc/PortableSundial.cs, Items/Summons/Mutant/PlanterasFruit.cs, Items/Tiles/FargoGlobalTile.cs, Items/Tiles/SiblingPylonTile.cs, Localization/en-US.hjson, NPCs/Abominationn.cs, NPCs/Deviantt.cs, NPCs/FargoGlobalNPC.cs, NPCs/Mutant.cs, NPCs/Squirrel.cs, NPCs/SuperDummy.cs
=> 1.4.4 porting fixes

NPCs/FargoGlobalNPC.cs
(NOTE: TODO: localization/correct text on conditions)
=> Fixed vanilla NPC shop additions 

Common/Systems/Recipes/RecipeGroups.cs, Items/Tiles/MultitaskCenter.cs
added new recipe groups such as "AnyWoodenTable", "AnyWoodenChair", and "AnyWoodenSink" and made multitask center use them in its recipe.
=> new recipe groups and made multitask center use them

Items/Tiles/ElementalAssembler.cs, Items/Tiles/ElementalAssemblerSheet.cs
literally just adds the kettle to the elemental assembler recipe and makes it so the elemental assembler can make tea cups, yippee.
=> adds kettle to elemental assembler recipe & effects

Items/Summons/Mutant/FleshyDoll.cs, Items/Summons/VanillaCopy/MechEye.cs
added rarity line for guide doll and changed line for mech eye
i genuinely don't know what I'm doing so i hope this doesn't automatically merge without review
=> Updates to Some Kind of Mechanical Eye and Guide Doll and Match Kit

Common/Systems/Recipes/NPCRecipeSystem.cs, Fargowiltas.cs, Items/CaughtNPCs/CaughtNPCItem.cs, Localization/en-US.hjson, Localization/ru-RU.hjson, Localization/zh-Hans.hjson
Remove quote field from CaughtNPCItem because it wasnt used for anything
Add town slime caught NPCs + recipes for gel and pink gel from them
=> Remove quote field from CaughtNPCItem + town slime caught npcs

Common/Configs/FargoServerConfig.cs, FargoWorld.cs, Localization/en-US.hjson, Localization/pt-BR.hjson, Localization/ru-RU.hjson, Localization/zh-Hans.hjson
Added new configurations for No Traps Seed, Don't Dig Up Seed, and Zenith Seed
Added Portuguese localization (thanks Harry)
=> Configurations for No Traps, DDU, and Zenith + Localization

Common/Systems/Recipes/ContainerRecipeSystem.cs, Common/Systems/Recipes/RecipeGroups.cs, Localization/en-US.hjson, Localization/pt-BR.hjson, Localization/ru-RU.hjson, Localization/zh-Hans.hjson
Added Portuguese Localization (thanks Harry)
=> Added Recipe Groups For Crates

Common/Systems/Recipes/ContainerRecipeSystem.cs, Common/Systems/Recipes/MiscRecipeSystem.cs, Common/Systems/Recipes/RecipeGroups.cs, Localization/en-US.hjson, Localization/pt-BR.hjson, Localization/ru-RU.hjson, Localization/zh-Hans.hjson, Utilities/RecipeHelper.cs
Added ItemXOrY to crates, removed sandstorm + flying carpet recipes that don't require crates
=> Changed Crate Recipe Groups, Removed Redundant Recipes

Content/NPCs/Abominationn.cs, Localization/en-US.hjson, Localization/pt-BR.hjson, Localization/ru-RU.hjson, Localization/zh-Hans.hjson
Abominationn now has unique dialogue when the player tries to cancel pillars before they've been defeated.
=> Abominationn Now Recognizes Pillars

Fargowiltas.cs
Abominationn's cancel command now works on Outsider's Portal
=> Abominationn Can Cancel Outsider's Portal

Common/Configs/FargoClientConfig.cs, Content/Items/FargoGlobalItem.cs, FargoPlayer.cs, Fargowiltas.cs, Localization/en-US.hjson, Localization/pt-BR.hjson, Localization/ru-RU.hjson, Localization/zh-Hans.hjson
Recon Scope view is now disabled if accessory visibility is toggled off
=> Recon Scope view toggle

FargoPlayer.cs
Fixed an issue where squirrel would not remember if you had any item at 30 stack
=> Squirrel Now Remembers Items At Thirty Stack

Fargowiltas.cs
Fix shimmer ingredients being jumbled around and potentially giving access to normally unavailable items
=> Animated Recipe Groups:
